name: LomindraApp
options:
  bundleIdPrefix: com.lomindra
packages:
  VikunjaSyncLib:
    path: ..

targets:
  LomindraApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - LomindraApp
    info:
      path: LomindraApp/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        BGTaskSchedulerPermittedIdentifiers:
          - com.lomindra.reminders.refresh
        NSRemindersUsageDescription: Reminders access is required to sync tasks.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - fetch
    settings:
      PRODUCT_NAME: Lomindra
      PRODUCT_BUNDLE_IDENTIFIER: com.lomindra.reminders
    dependencies:
      - package: VikunjaSyncLib
        product: VikunjaSyncLib

schemes:
  LomindraApp:
    build:
      targets:
        LomindraApp: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
